# _c.f._ https://pnpm.io/settings

minimumReleaseAge: 10080 # 7 jours (exprimé en minutes)
preferFrozenLockfile: true

minimumReleaseAgeExclude:
  - immutable@5.1.5
  # Renovate security update: vite@8.0.16
  - vite@8.0.16
