# _c.f._ https://pnpm.io/settings

minimumReleaseAge: 10080 # 7 jours (exprimé en minutes)
preferFrozenLockfile: true

minimumReleaseAgeExclude:
  - immutable@5.1.5
  # Renovate security update: dompurify@3.4.11
  - dompurify@3.4.11
